export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as User } from './User';
export { default as Network } from './Network';
export { default as OtherUser } from './OtherUser';
export { default as Education } from '../components/user/Education';
export { default as Award } from '../components/user/Award';
export { default as Project } from '../components/user/Project';
export { default as Certificate } from '../components/user/Certificate';